apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: coldcase
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: coldcase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devdamian/coldcase-backend:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: coldcase-secrets
                  key: DATABASE_URL
            - name: ALLOWED_ORIGINS
              value: "http://ccase.tech,https://ccase.tech,http://api.ccase.tech,https://api.ccase.tech,http://104.64.127.24,http://104.64.127.23,http://104.64.127.23:3000"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: OSRM_BASE_URL
              value: "http://osrm:5000"
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coldcase-secrets
                  key: JWT_SECRET
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coldcase-secrets
                  key: LLM_API_KEY
            - name: LLM_BASE_URL
              value: "https://api.groq.com/openai/v1"
            - name: LLM_MODEL_NAME
              value: "llama-3.3-70b-versatile"
            - name: LLM_BOOST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coldcase-secrets
                  key: LLM_BOOST_API_KEY
            - name: LLM_BOOST_BASE_URL
              value: "https://api.groq.com/openai/v1"
            - name: LLM_BOOST_MODEL_NAME
              value: "llama-3.3-70b-versatile"
            - name: ZEP_API_URL
              value: "https://api.getzep.com"
            - name: ZEP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coldcase-secrets
                  key: ZEP_API_KEY
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # Define standard readiness and liveness probes to showcase self-healing
          readinessProbe:
            httpGet:
              path: /health # We have a MuninController or health endpoint
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
